#!/bin/sh

# script/setup: First time setup

set -e

cd "$(dirname "$0")/.."

make_zsh_default_shell() {
  command -v zsh >/dev/null 2>&1 && ! [ "$SHELL" = "$(command -v zsh)" ] && {
    echo "=> Make ZSH the default shell."
    chsh -s "$(command -v zsh)"
  }
}

setup() {
  echo "> Setup starting."
  script/bootstrap
  make_zsh_default_shell
  echo "> Setup complete."
}

setup
